# Generated by Django 4.2.4 on 2023-10-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmailsend', '0002_client_owner_mailinglog_owner_mailingsettings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='body_email',
            field=models.TextField(blank=True, null=True, verbose_name='Тело письма'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='subject_email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема письма'),
        ),
    ]
