# Generated by Django 4.2.4 on 2023-10-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmailsend', '0003_mailingsettings_body_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmailsend.mailingsettings', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='client',
            field=models.ManyToManyField(to='appmailsend.client'),
        ),
    ]
